name: video_conference
description: 'Video conference app'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  camera: ^0.11.0+1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
